# Generated by Django 5.0.6 on 2024-05-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_usercapibara'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCapibara',
            new_name='User',
        ),
    ]
