# Generated by Django 5.0.6 on 2024-05-17 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasification',
            fields=[
                ('clasificationId', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Clasificación')),
                ('name', models.CharField(max_length=100, verbose_name='Clasificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('productTypeId', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Tipo Mueble')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de Mueble')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombre', models.CharField(max_length=100)),
                ('stock_disponible', models.IntegerField()),
                ('image', models.ImageField(upload_to='capibara/images/')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('largo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('alto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('materiales_planchas', models.IntegerField(default=0)),
                ('materiales_tornillos', models.IntegerField(default=0)),
                ('pegamento', models.IntegerField(default=0)),
                ('manillas', models.IntegerField(default=0)),
                ('bisagras', models.IntegerField(default=0)),
                ('patas_goma', models.IntegerField(default=0)),
                ('riel', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('clasificacion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.clasification')),
                ('tipo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zona_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zona_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zona_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zona_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.product')),
            ],
        ),
    ]
