# Generated by Django 5.0.6 on 2024-05-17 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('productClassId', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Clase Mueble')),
                ('name', models.CharField(max_length=100, verbose_name='Clase de Mueble')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='clase',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.productclass'),
        ),
    ]
