# Generated by Django 5.0.6 on 2024-05-17 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_productclass_product_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clase',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.productclass'),
        ),
    ]
