# Generated by Django 5.0.6 on 2024-05-18 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_product_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('emailCliente', models.CharField(max_length=100)),
                ('fechaOrden', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False, null=True)),
                ('transactionId', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('emailCliente', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('codigoPostal', models.CharField(max_length=100)),
                ('fechaCompra', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.orden')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('fechaAñadido', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.product')),
            ],
        ),
    ]
